### PR TITLE
yarr

### PR DESCRIPTION
**Pull request by bahstrike**
a lot of simplification and built-in windows audio support.  im using qbplay.cs in my own QB project converted to c#

### CODE REVIEW

**Review by bahstrike — COMMENTED** [review]
checked for no dumb haxx, should be aight.   all converted to a static class tho-  state machine.  but like with the built-in windows audio it ought to be anyway

**Comment by nivs1978** [comment]
The point of the application was to be able to run on Linux and Mac, not just Windows. Also it was meant as a documentation to the QBasic sound files, with classes representing the commands where the string is first parsed into a list of commands and the commands are then converted into the WAV format. This is how compilers works as well. First you scan the source and build a list or tree or cammands and functions and then you execute them. So I will not accept the pull request you made. You can make a fork of it and have your own repository with a Windows QBasic play library. Also the comments contain leet english, swearing and stuff like that and I do not want that my repositorys.

**Comment by bahstrike** [comment]
werd bruh   the pull request is from a fork, ill leave it up  in case anyone wants a drop-in solution.  u may consider diffing files and pulling in some fixes;   your support for spaces is non-existant and you also forgot the <  and  >  for octave shifts.  i wont be offended if u remove the   "leet english, swearing and stuff".  different levels bruh

**Comment by bahstrike** [comment]
also, i know how compilers work-  cant school me in that regard. fix your parser.

cgcp

**Comment by bahstrike** [comment]
i think ur *.wav  subchunk stuff is screwed up, too.  the wav files can be played by VLC but i think other applications have no idea what length they are.  u should have serialized the structures differently

**Comment by bahstrike** [comment]
ok cool-  thanks for your condescending review.

i don't need to be schooled on how "compilers works" as i have written a couple before (and on much more complex languages than QB PLAY.. LOL).

personally, i'd prefer to slough off all the bloat since the **spec for QB PLAY is set in stone** and there is no need for making it beautiful and expandable-  or even readable, for that matter. but i concede that many people think the code is more important than the product.

please just fix your parser-  i have created bug entries for you to implement the "right" way  *scoff*

**Pull request closed without merging**
